def test_function():
    def inner_function():
        print("Я в области видимости функции test_function")

    inner_function()


test_function()
#inner_function() тут он ругается потому что, он так сказать локальный, и существует внутри функции ток
